/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SigninSplatRouteImport } from './routes/signin.$'
import { Route as AuthRecipeRouteImport } from './routes/_auth/recipe'
import { Route as AuthMyRecipesRouteRouteImport } from './routes/_auth/my-recipes/route'
import { Route as AuthMyIngredientsRouteRouteImport } from './routes/_auth/my-ingredients/route'
import { Route as AuthMyRecipesIndexRouteImport } from './routes/_auth/my-recipes/index'
import { Route as AuthCreateRecipeIndexRouteImport } from './routes/_auth/create-recipe/index'
import { Route as AuthCreateCocktailIndexRouteImport } from './routes/_auth/create-cocktail/index'
import { Route as AuthUserRecipeRecipeIdRouteImport } from './routes/_auth/user-recipe/$recipeId'
import { Route as AuthMyIngredientsFoodRouteImport } from './routes/_auth/my-ingredients/food'
import { Route as AuthMyIngredientsDrinksRouteImport } from './routes/_auth/my-ingredients/drinks'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninSplatRoute = SigninSplatRouteImport.update({
  id: '/signin/$',
  path: '/signin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecipeRoute = AuthRecipeRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMyRecipesRouteRoute = AuthMyRecipesRouteRouteImport.update({
  id: '/my-recipes',
  path: '/my-recipes',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMyIngredientsRouteRoute = AuthMyIngredientsRouteRouteImport.update({
  id: '/my-ingredients',
  path: '/my-ingredients',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMyRecipesIndexRoute = AuthMyRecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMyRecipesRouteRoute,
} as any)
const AuthCreateRecipeIndexRoute = AuthCreateRecipeIndexRouteImport.update({
  id: '/create-recipe/',
  path: '/create-recipe/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCreateCocktailIndexRoute = AuthCreateCocktailIndexRouteImport.update({
  id: '/create-cocktail/',
  path: '/create-cocktail/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthUserRecipeRecipeIdRoute = AuthUserRecipeRecipeIdRouteImport.update({
  id: '/user-recipe/$recipeId',
  path: '/user-recipe/$recipeId',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMyIngredientsFoodRoute = AuthMyIngredientsFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => AuthMyIngredientsRouteRoute,
} as any)
const AuthMyIngredientsDrinksRoute = AuthMyIngredientsDrinksRouteImport.update({
  id: '/drinks',
  path: '/drinks',
  getParentRoute: () => AuthMyIngredientsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-ingredients': typeof AuthMyIngredientsRouteRouteWithChildren
  '/my-recipes': typeof AuthMyRecipesRouteRouteWithChildren
  '/recipe': typeof AuthRecipeRoute
  '/signin/$': typeof SigninSplatRoute
  '/my-ingredients/drinks': typeof AuthMyIngredientsDrinksRoute
  '/my-ingredients/food': typeof AuthMyIngredientsFoodRoute
  '/user-recipe/$recipeId': typeof AuthUserRecipeRecipeIdRoute
  '/create-cocktail/': typeof AuthCreateCocktailIndexRoute
  '/create-recipe/': typeof AuthCreateRecipeIndexRoute
  '/my-recipes/': typeof AuthMyRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-ingredients': typeof AuthMyIngredientsRouteRouteWithChildren
  '/recipe': typeof AuthRecipeRoute
  '/signin/$': typeof SigninSplatRoute
  '/my-ingredients/drinks': typeof AuthMyIngredientsDrinksRoute
  '/my-ingredients/food': typeof AuthMyIngredientsFoodRoute
  '/user-recipe/$recipeId': typeof AuthUserRecipeRecipeIdRoute
  '/create-cocktail': typeof AuthCreateCocktailIndexRoute
  '/create-recipe': typeof AuthCreateRecipeIndexRoute
  '/my-recipes': typeof AuthMyRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_auth/my-ingredients': typeof AuthMyIngredientsRouteRouteWithChildren
  '/_auth/my-recipes': typeof AuthMyRecipesRouteRouteWithChildren
  '/_auth/recipe': typeof AuthRecipeRoute
  '/signin/$': typeof SigninSplatRoute
  '/_auth/my-ingredients/drinks': typeof AuthMyIngredientsDrinksRoute
  '/_auth/my-ingredients/food': typeof AuthMyIngredientsFoodRoute
  '/_auth/user-recipe/$recipeId': typeof AuthUserRecipeRecipeIdRoute
  '/_auth/create-cocktail/': typeof AuthCreateCocktailIndexRoute
  '/_auth/create-recipe/': typeof AuthCreateRecipeIndexRoute
  '/_auth/my-recipes/': typeof AuthMyRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-ingredients'
    | '/my-recipes'
    | '/recipe'
    | '/signin/$'
    | '/my-ingredients/drinks'
    | '/my-ingredients/food'
    | '/user-recipe/$recipeId'
    | '/create-cocktail/'
    | '/create-recipe/'
    | '/my-recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-ingredients'
    | '/recipe'
    | '/signin/$'
    | '/my-ingredients/drinks'
    | '/my-ingredients/food'
    | '/user-recipe/$recipeId'
    | '/create-cocktail'
    | '/create-recipe'
    | '/my-recipes'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/my-ingredients'
    | '/_auth/my-recipes'
    | '/_auth/recipe'
    | '/signin/$'
    | '/_auth/my-ingredients/drinks'
    | '/_auth/my-ingredients/food'
    | '/_auth/user-recipe/$recipeId'
    | '/_auth/create-cocktail/'
    | '/_auth/create-recipe/'
    | '/_auth/my-recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SigninSplatRoute: typeof SigninSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin/$': {
      id: '/signin/$'
      path: '/signin/$'
      fullPath: '/signin/$'
      preLoaderRoute: typeof SigninSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/recipe': {
      id: '/_auth/recipe'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof AuthRecipeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/my-recipes': {
      id: '/_auth/my-recipes'
      path: '/my-recipes'
      fullPath: '/my-recipes'
      preLoaderRoute: typeof AuthMyRecipesRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/my-ingredients': {
      id: '/_auth/my-ingredients'
      path: '/my-ingredients'
      fullPath: '/my-ingredients'
      preLoaderRoute: typeof AuthMyIngredientsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/my-recipes/': {
      id: '/_auth/my-recipes/'
      path: '/'
      fullPath: '/my-recipes/'
      preLoaderRoute: typeof AuthMyRecipesIndexRouteImport
      parentRoute: typeof AuthMyRecipesRouteRoute
    }
    '/_auth/create-recipe/': {
      id: '/_auth/create-recipe/'
      path: '/create-recipe'
      fullPath: '/create-recipe/'
      preLoaderRoute: typeof AuthCreateRecipeIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/create-cocktail/': {
      id: '/_auth/create-cocktail/'
      path: '/create-cocktail'
      fullPath: '/create-cocktail/'
      preLoaderRoute: typeof AuthCreateCocktailIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/user-recipe/$recipeId': {
      id: '/_auth/user-recipe/$recipeId'
      path: '/user-recipe/$recipeId'
      fullPath: '/user-recipe/$recipeId'
      preLoaderRoute: typeof AuthUserRecipeRecipeIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/my-ingredients/food': {
      id: '/_auth/my-ingredients/food'
      path: '/food'
      fullPath: '/my-ingredients/food'
      preLoaderRoute: typeof AuthMyIngredientsFoodRouteImport
      parentRoute: typeof AuthMyIngredientsRouteRoute
    }
    '/_auth/my-ingredients/drinks': {
      id: '/_auth/my-ingredients/drinks'
      path: '/drinks'
      fullPath: '/my-ingredients/drinks'
      preLoaderRoute: typeof AuthMyIngredientsDrinksRouteImport
      parentRoute: typeof AuthMyIngredientsRouteRoute
    }
  }
}

interface AuthMyIngredientsRouteRouteChildren {
  AuthMyIngredientsDrinksRoute: typeof AuthMyIngredientsDrinksRoute
  AuthMyIngredientsFoodRoute: typeof AuthMyIngredientsFoodRoute
}

const AuthMyIngredientsRouteRouteChildren: AuthMyIngredientsRouteRouteChildren =
  {
    AuthMyIngredientsDrinksRoute: AuthMyIngredientsDrinksRoute,
    AuthMyIngredientsFoodRoute: AuthMyIngredientsFoodRoute,
  }

const AuthMyIngredientsRouteRouteWithChildren =
  AuthMyIngredientsRouteRoute._addFileChildren(
    AuthMyIngredientsRouteRouteChildren,
  )

interface AuthMyRecipesRouteRouteChildren {
  AuthMyRecipesIndexRoute: typeof AuthMyRecipesIndexRoute
}

const AuthMyRecipesRouteRouteChildren: AuthMyRecipesRouteRouteChildren = {
  AuthMyRecipesIndexRoute: AuthMyRecipesIndexRoute,
}

const AuthMyRecipesRouteRouteWithChildren =
  AuthMyRecipesRouteRoute._addFileChildren(AuthMyRecipesRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthMyIngredientsRouteRoute: typeof AuthMyIngredientsRouteRouteWithChildren
  AuthMyRecipesRouteRoute: typeof AuthMyRecipesRouteRouteWithChildren
  AuthRecipeRoute: typeof AuthRecipeRoute
  AuthUserRecipeRecipeIdRoute: typeof AuthUserRecipeRecipeIdRoute
  AuthCreateCocktailIndexRoute: typeof AuthCreateCocktailIndexRoute
  AuthCreateRecipeIndexRoute: typeof AuthCreateRecipeIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthMyIngredientsRouteRoute: AuthMyIngredientsRouteRouteWithChildren,
  AuthMyRecipesRouteRoute: AuthMyRecipesRouteRouteWithChildren,
  AuthRecipeRoute: AuthRecipeRoute,
  AuthUserRecipeRecipeIdRoute: AuthUserRecipeRecipeIdRoute,
  AuthCreateCocktailIndexRoute: AuthCreateCocktailIndexRoute,
  AuthCreateRecipeIndexRoute: AuthCreateRecipeIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SigninSplatRoute: SigninSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
